#ifndef GENERALS_AND_ZERO_HOUR_COMMON_DEFINES_HPP
#define GENERALS_AND_ZERO_HOUR_COMMON_DEFINES_HPP

#ifndef NDEBUG
    #define GENERALS_AND_ZERO_HOUR_DEBUG
#endif // NDEBUG

#endif // GENERALS_AND_ZERO_HOUR_COMMON_DEFINES_HPP